#ifndef CNBIROS_NAVIGATION_FLAGS_HPP
#define CNBIROS_NAVIGATION_FLAGS_HPP

#define CNBIROS_FORCEFIELD_ROBOT_SIZE			0.6f
#define CNBIROS_FORCEFIELD_ROBOT_SECTOR			M_PI/9.0f

#define CNBIROS_FORCEFIELD_STRENGTH_ATTRACTORS	0.6f
//#define CNBIROS_FORCEFIELD_STRENGTH_REPELLORS	1.0f
#define CNBIROS_FORCEFIELD_STRENGTH_REPELLORS	0.3f	// no kinect
#define CNBIROS_FORCEFIELD_DECAY_ATTRACTORS		5.0f
//#define CNBIROS_FORCEFIELD_DECAY_REPELLORS		1.0f
#define CNBIROS_FORCEFIELD_DECAY_REPELLORS		0.5f	// no kinect
#define CNBIROS_FORCEFIELD_NUMBER_SECTORS 		41

#define CNBIROS_FORCEFIELD_VELOCITY_MAX			0.15f
#define CNBIROS_FORCEFIELD_VELOCITY_DECAY		0.05f
//#define CNBIROS_FORCEFIELD_VELOCITY_SAFEZONE 	0.2f
#define CNBIROS_FORCEFIELD_VELOCITY_SAFEZONE 	0.05f
//#define CNBIROS_FORCEFIELD_VELOCITY_AUDACITY 	100.0f
#define CNBIROS_FORCEFIELD_VELOCITY_AUDACITY 	200.0f // no kinect

#endif
