#ifndef CNBIROS_NAVIGATION_FLAGS_HPP
#define CNBIROS_NAVIGATION_FLAGS_HPP

#define CNBIROS_FORCEFIELD_ROBOT_SIZE			0.6f
#define CNBIROS_FORCEFIELD_ROBOT_SECTOR			M_PI/9.0f

#define CNBIROS_FORCEFIELD_STRENGTH_ATTRACTORS	3.0f
//#define CNBIROS_FORCEFIELD_STRENGTH_REPELLORS	1.0f
#define CNBIROS_FORCEFIELD_STRENGTH_REPELLORS	2.0f
#define CNBIROS_FORCEFIELD_DECAY_ATTRACTORS		5.0f
#define CNBIROS_FORCEFIELD_DECAY_REPELLORS		0.7f
#define CNBIROS_FORCEFIELD_NUMBER_SECTORS 		9

#define CNBIROS_FORCEFIELD_VELOCITY_MAX			0.1f
#define CNBIROS_FORCEFIELD_VELOCITY_DECAY		0.05f
//#define CNBIROS_FORCEFIELD_VELOCITY_SAFEZONE 	0.2f
#define CNBIROS_FORCEFIELD_VELOCITY_SAFEZONE 	0.1f
#define CNBIROS_FORCEFIELD_VELOCITY_AUDACITY 	50.0f

#endif
