#ifndef CNBIROS_NAVIGATION_FLAGS_HPP
#define CNBIROS_NAVIGATION_FLAGS_HPP


#define CNBIROS_NAVIGATION_FUSIONGRID_X		5.0f
#define CNBIROS_NAVIGATION_FUSIONGRID_Y		5.0f
#define CNBIROS_NAVIGATION_FUSIONGRID_R		0.05f

#define CNBIROS_FORCEFIELD_TARGETLAYER		"fusion"
#define CNBIROS_FORCEFIELD_STRENGTH			1.0f
#define CNBIROS_FORCEFIELD_DECAY			1.0f
#define CNBIROS_FORCEFIELD_OBSTRUCTION		0.8f

#define CNBIROS_FORCEFIELD_VELOCITY_MAX		0.1f
#define CNBIROS_FORCEFIELD_VELOCITY_DECAY	2.0f
#define CNBIROS_FORCEFIELD_VELOCITY_SAFEZONE 0.2f

#endif
